In [86]:
#True hyperparameters
theta = 0.78
c1 = 0.23
c2 = 0.65
d1 = 1 - c1
d2 = 1 - c2

In [87]:
num_iterations = 500

In [88]:
import numpy as np

In [89]:
coefficients = np.zeros(1)
first_moment = np.zeros(num_iterations+1)

In [90]:
first_moment[0] = 0.5
coefficients[0] = 1

In [91]:
true_p = theta * c1 + (1 - theta) * c2

In [92]:
def moment(coefficient):
    M1 = 0
    for i in range(len(coefficient)):
        M1 += coefficient[i] / (i+2)
    return M1

In [93]:
def probability(coefficient):
    p = 0
    for i in range(len(coefficient)):
        p += coefficient[i] / (i+1)
    return p

In [94]:
import random

In [95]:
epsilon = 0.000001

In [96]:
for i in range(num_iterations):
    print(probability(coefficients))
    print(coefficients)
    r = random.uniform(0, 1)
    if(r < true_p):
        denominator = (c1 - c2) * first_moment[i] + c2
        coefficients = np.append(coefficients, coefficients[i] * (c1-c2))
        for j in range(i, 0, -1):
            coefficients[j] = coefficients[j-1] * (c1-c2) + c2*coefficients[j]
        coefficients[0] = c2*coefficients[0]
        coefficients = coefficients / probability(coefficients)
    else:
        denominator = (d1 - d2) * first_moment[i] + d2
        coefficients = np.append(coefficients, coefficients[i] * (d1-d2))
        for j in range(i, 0, -1):
            coefficients[j] = coefficients[j-1] * (d1-d2) + d2*coefficients[j]
        coefficients[0] = d2*coefficients[0]
        coefficients = coefficients / probability(coefficients)
    first_moment[i+1] = moment(coefficients)      
            

1.0
[1.]
1.0
[ 1.47727273 -0.95454545]
1.0
[ 2.02832453 -2.6212194   0.8468555 ]
1.0
[ 2.62577925 -5.08997208  3.28890504 -0.70837955]
1.0000000000000002
[ 1.9362167  -1.42982157 -2.07874058  2.38788662 -0.62682024]
1.0
[ 1.36940788  0.63203441 -2.68371532 -0.07539535  1.58330228 -0.53198957]
0.9999999999999999
[ 0.92733625  1.54080485 -1.30375795 -2.23188773  1.01091386  0.9263647
 -0.43230353]
1.0
[ 0.60135189  1.72079156  0.35355221 -2.46185854 -1.08123125  1.38738145
  0.44052937 -0.33640424]
1.0000000000000004
[ 0.37416972  1.51970469  1.50482646 -1.2678212  -2.51092165  0.05593952
  1.31000186  0.11960887 -0.25117862]
0.9999999999999998
[ 0.22415217  1.17938525  1.99397279  0.3222796  -2.41561606 -1.7715364
  0.82499064  1.01338585 -0.06448819 -0.18056693]
0.9999999999999999
[ 0.12983798  0.83895309  1.9747665   1.57266473 -1.17520946 -2.70521208
 -0.75350656  1.1604354   0.66703859 -0.14941665 -0.12550998]
0.9999999999999999
[ 0.07304719  0.55965388  1.67740561  2.21799607  0.40

  6.32774700e-16]
1.0000292724499265
[ 8.54683666e-14  7.83416197e-12  3.51541405e-10  1.02871694e-08
  2.20626264e-07  3.69477635e-06  5.02631954e-05  5.70464744e-04
  5.50464567e-03  4.57839689e-02  3.31537626e-01  2.10518294e+00
  1.17767866e+01  5.81814672e+01  2.53821207e+02  9.74721705e+02
  3.26974196e+03  9.43471407e+03  2.26860745e+04  4.20969026e+04
  4.50122986e+04 -4.79887855e+04 -3.98260882e+05 -1.14970358e+06
 -1.99225827e+06 -1.32439713e+06  4.17594333e+06  1.71222422e+07
  3.12958139e+07  2.08368720e+07 -5.50716466e+07 -2.02115650e+08
 -2.95691796e+08 -4.51436070e+07  7.72459176e+08  1.73540755e+09
  1.37119144e+09 -1.92433996e+09 -7.10141811e+09 -8.11406475e+09
  2.71986935e+09  2.33321317e+10  3.22299499e+10  7.80545428e+08
 -6.63846650e+10 -1.00857636e+11 -1.54057964e+10  1.71318607e+11
  2.62864479e+11  4.00592013e+10 -4.08940767e+11 -5.81146874e+11
 -3.18666242e+10  8.97437226e+11  1.08537984e+12 -1.47752620e+11
 -1.76950449e+12 -1.66964456e+12  7.54001618e+11  3.0

  1.41371102e-23  2.32846520e-24]
1.122440287626348
[-5.10682663e-22 -6.89185895e-20 -4.58500008e-18 -2.00411159e-16
 -6.47211843e-15 -1.64640526e-13 -3.43478616e-12 -6.04127808e-11
 -9.13936688e-10 -1.20729373e-08 -1.40895492e-07 -1.46616192e-06
 -1.37050237e-05 -1.15764983e-04 -8.87878734e-04 -6.20671250e-03
 -3.96623634e-02 -2.32185991e-01 -1.24688835e+00 -6.14603175e+00
 -2.77961380e+01 -1.15176632e+02 -4.35984517e+02 -1.50014198e+03
 -4.65302598e+03 -1.28264736e+04 -3.06049545e+04 -5.96646617e+04
 -7.94211549e+04  3.10007179e+03  4.35148489e+05  1.64522692e+06
  3.90472816e+06  6.02395474e+06  2.68435130e+06 -1.79180605e+07
 -6.90849279e+07 -1.40028250e+08 -1.42671202e+08  1.31745527e+08
  9.15409325e+08  2.03264020e+09  2.15371307e+09 -1.47976417e+09
 -1.10247787e+10 -2.22226692e+10 -1.78472405e+10  2.77195724e+10
  1.17102803e+11  1.76960980e+11  4.38073928e+10 -4.05598501e+11
 -9.52509894e+11 -8.21887423e+11  8.81979340e+11  3.78174567e+12
  4.85832418e+12 -3.49408522e+11 -1.21

  6.30335534e-31  3.78678646e-32 -3.74223603e-33 -3.24069925e-34]
0.7263012400436076
[ 1.21188105e-31  2.07623191e-29  1.75906339e-27  9.82449687e-26
  4.06821171e-24  1.33190111e-22  3.59020501e-21  8.19307041e-20
  1.61535218e-18  2.79427142e-17  4.29223263e-16  5.91154875e-15
  7.35763708e-14  8.32946455e-13  8.62369565e-12  8.20252023e-11
  7.19529538e-10  5.83990450e-09  4.39745396e-08  3.07905988e-07
  2.00843275e-06  1.22221945e-05  6.94637595e-05  3.68961543e-04
  1.83204663e-03  8.50249230e-03  3.68554384e-02  1.49008053e-01
  5.60669837e-01  1.95666448e+00  6.30082532e+00  1.85732607e+01
  4.94725646e+01  1.16370156e+02  2.30480463e+02  3.36471596e+02
  1.39320483e+02 -1.24213544e+03 -5.65808278e+03 -1.55046264e+04
 -3.01763506e+04 -3.56049918e+04  1.44027738e+04  2.10744073e+05
  6.43055671e+05  1.19579964e+06  1.11757457e+06 -1.40479990e+06
 -8.69329063e+06 -2.02323419e+07 -2.54495070e+07  3.07479353e+06
  1.00295304e+08  2.58864448e+08  3.34937074e+08 -1.10310518e+07
 -1.1

 -1.76302466e-40  5.19152807e-41  5.25407660e-42  1.61663895e-43]
4.472179424101526
[-2.94546924e-41 -6.25345777e-39 -6.58214286e-37 -4.57903674e-35
 -2.36826499e-33 -9.71178046e-32 -3.28881885e-30 -9.45836885e-29
 -2.35780221e-27 -5.17456522e-26 -1.01211042e-24 -1.78175139e-23
 -2.84605815e-22 -4.15286112e-21 -5.56715042e-20 -6.88990612e-19
 -7.90510618e-18 -8.43904596e-17 -8.40900991e-16 -7.84268880e-15
 -6.86291479e-14 -5.64679193e-13 -4.37680035e-12 -3.20098547e-11
 -2.21207680e-10 -1.44623231e-09 -8.95464778e-09 -5.25539630e-08
 -2.92554705e-07 -1.54552282e-06 -7.75093581e-06 -3.69065809e-05
 -1.66837717e-04 -7.15801920e-04 -2.91304912e-03 -1.12347454e-02
 -4.10074781e-02 -1.41395842e-01 -4.59361611e-01 -1.40098594e+00
 -3.99029637e+00 -1.05315369e+01 -2.54422638e+01 -5.50728044e+01
 -1.02318025e+02 -1.45484854e+02 -8.21352176e+01  3.81544593e+02
  1.87076562e+03  5.32167574e+03  1.12369248e+04  1.71322091e+04
  1.20505491e+04 -3.07117432e+04 -1.53886091e+05 -3.86079517e+05
 -6.44

  2.21899586e-49  2.28091013e-50  6.79420038e-52]
0.8657380921458498
[-2.38635115e-50 -5.75147341e-48 -6.87923664e-46 -5.44389239e-44
 -3.20620118e-42 -1.49886356e-40 -5.79294913e-39 -1.90363367e-37
 -5.42888926e-36 -1.36477983e-34 -3.06176113e-33 -6.19066386e-32
 -1.13735700e-30 -1.91163798e-29 -2.95642520e-28 -4.22789311e-27
 -5.61473734e-26 -6.95018952e-25 -8.04525577e-24 -8.73384112e-23
 -8.91447406e-22 -8.57413183e-21 -7.78680987e-20 -6.68928585e-19
 -5.44429539e-18 -4.20397317e-17 -3.08375270e-16 -2.15120298e-15
 -1.42852052e-14 -9.03772476e-14 -5.45141192e-13 -3.13684103e-12
 -1.72271253e-11 -9.03272911e-11 -4.52276378e-10 -2.16272178e-09
 -9.87591047e-09 -4.30554756e-08 -1.79128899e-07 -7.10724422e-07
 -2.68674847e-06 -9.66459511e-06 -3.30229297e-05 -1.06930759e-04
 -3.27078934e-04 -9.40855668e-04 -2.52875577e-03 -6.28822501e-03
 -1.42344385e-02 -2.84598367e-02 -4.69060699e-02 -4.99488856e-02
  3.13305114e-02  3.70980401e-01  1.30340855e+00  3.25606613e+00
  6.23273481e+00  8.2

  9.55946860e-55  1.94518500e-56 -4.53329001e-57 -2.36519479e-58]
1.8151239788719582
[-1.60786961e-54 -4.02511604e-52 -5.00062990e-50 -4.11036317e-48
 -2.51447448e-46 -1.22096280e-44 -4.90140242e-43 -1.67293488e-41
 -4.95535163e-40 -1.29385242e-38 -3.01467686e-37 -6.33053377e-36
 -1.20786218e-34 -2.10826315e-33 -3.38581200e-32 -5.02772749e-31
 -6.93266990e-30 -8.90961361e-29 -1.07067317e-27 -1.20652522e-26
 -1.27818930e-25 -1.27587111e-24 -1.20236491e-23 -1.07164960e-22
 -9.04773647e-22 -7.24609578e-21 -5.51164187e-20 -3.98603595e-19
 -2.74343063e-18 -1.79841621e-17 -1.12363248e-16 -6.69475815e-16
 -3.80543799e-15 -2.06423222e-14 -1.06871272e-13 -5.28093643e-13
 -2.49020515e-12 -1.12015466e-11 -4.80383185e-11 -1.96244250e-10
 -7.62770322e-10 -2.81631745e-09 -9.85636677e-09 -3.25996546e-08
 -1.01480649e-07 -2.95574757e-07 -7.98395969e-07 -1.97165457e-06
 -4.33856486e-06 -8.04931653e-06 -1.06344445e-05 -5.33815544e-07
  5.70262911e-05  2.41281247e-04  6.82788977e-04  1.47452509e-03
  2.2

 -2.63292559e-63 -3.74857203e-64]
1.330575841024821
[ 1.41484765e-58  3.67512120e-56  4.73783460e-54  4.04133292e-52
  2.56571281e-50  1.29302381e-48  5.38758811e-47  1.90875143e-45
  5.86904195e-44  1.59083678e-42  3.84817822e-41  8.38983173e-40
  1.66208548e-38  3.01236708e-37  5.02361712e-36  7.74673964e-35
  1.10933715e-33  1.48067332e-32  1.84805710e-31  2.16308107e-30
  2.38028169e-29  2.46805323e-28  2.41610091e-27  2.23706074e-26
  1.96211605e-25  1.63252721e-24  1.29008644e-23  9.69322034e-23
  6.93130374e-22  4.72070967e-21  3.06433434e-20  1.89686404e-19
  1.12017381e-18  6.31252737e-18  3.39506108e-17  1.74264716e-16
  8.53504680e-16  3.98721273e-15  1.77555109e-14  7.53026561e-14
  3.03783254e-13  1.16375880e-12  4.22393152e-12  1.44800677e-11
  4.66803080e-11  1.40630296e-10  3.92163279e-10  9.96600549e-10
  2.24268060e-09  4.19029349e-09  5.23522637e-09 -2.23495608e-09
 -4.18001852e-08 -1.68841560e-07 -4.76706293e-07 -1.02813933e-06
 -1.54310047e-06 -5.56025429e-07  6.10

 -9.05338028e-70 -1.49114499e-70]
16.35586578010504
[ 1.02693940e-62  2.84572807e-60  3.91531728e-58  3.56583119e-56
  2.41814493e-54  1.30230766e-52  5.80142693e-51  2.19851820e-49
  7.23438668e-48  2.09959061e-46  5.44085217e-45  1.27146410e-43
  2.70139639e-42  5.25389327e-41  9.40789618e-40  1.55873588e-38
  2.39983414e-37  3.44619640e-36  4.63096828e-35  5.84025923e-34
  6.93001029e-33  7.75473680e-32  8.20001544e-31  8.20853470e-30
  7.79157741e-29  7.02302901e-28  6.01901679e-27  4.91053993e-26
  3.81749588e-25  2.83049657e-24  2.00317653e-23  1.35405624e-22
  8.74691620e-22  5.40213679e-21  3.19088370e-20  1.80294571e-19
  9.74581272e-19  5.03960002e-18  2.49247263e-17  1.17858400e-16
  5.32523956e-16  2.29728261e-15  9.45159893e-15  3.70310067e-14
  1.37889339e-13  4.86672295e-13  1.62214116e-12  5.07971895e-12
  1.48315268e-11  3.98984648e-11  9.68865426e-11  2.03885931e-10
  3.34310805e-10  2.44869213e-10 -9.98290923e-10 -6.00925864e-09
 -2.03852569e-08 -5.21252674e-08 -1.01

In [84]:
print(denominator)

0.7692737610285398


In [85]:
first_moment

array([0.5       , 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700437,
       0.98700437, 0.98700437, 0.98700437, 0.98700437, 0.98700438,
       0.98700436, 0.98700438, 0.98700439, 0.98700442, 0.98700453,
       0.98700477, 0.98700538, 0.98700675, 0.98700981, 0.98722188,
       0.98747448, 0.98704284, 0.98708462, 0.9871549 , 0.98726

In [13]:
moment(coefficients)   

0.42872236083750576

In [285]:
print(list(range(1, 0, -1)))

[1]
